"""Aumentar tamaño de columnas en Vehicle

Revision ID: 682b76ecfa44
Revises: fd2f9d04af5c
Create Date: 2025-03-19 14:58:46.439384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682b76ecfa44'
down_revision = 'fd2f9d04af5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['model'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
